//
// AccountCreateRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountCreateRes: Codable, JSONEncodable, Hashable {

    internal var responseAccountCreate: ResponseAccountCreate

    internal init(responseAccountCreate: ResponseAccountCreate) {
        self.responseAccountCreate = responseAccountCreate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseAccountCreate = "response_account_create"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseAccountCreate, forKey: .responseAccountCreate)
    }
}

