//
// AccountUpdateRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountUpdateRes: Codable, JSONEncodable, Hashable {

    internal var responseAccountUpdate: ResponseAccountUpdate

    internal init(responseAccountUpdate: ResponseAccountUpdate) {
        self.responseAccountUpdate = responseAccountUpdate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseAccountUpdate = "response_account_update"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseAccountUpdate, forKey: .responseAccountUpdate)
    }
}

