//
// AccountHierarchyEnquiryRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountHierarchyEnquiryRes: Codable, JSONEncodable, Hashable {

    internal var responseAccountHierarchy: ResponseAccountHierarchy

    internal init(responseAccountHierarchy: ResponseAccountHierarchy) {
        self.responseAccountHierarchy = responseAccountHierarchy
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseAccountHierarchy = "response_account_hierarchy"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseAccountHierarchy, forKey: .responseAccountHierarchy)
    }
}

