//
// AccountCreateBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountCreateBody: Codable, JSONEncodable, Hashable {

    static let customerIdRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let cardTypeRule = StringRule(minLength: 1, maxLength: 7, pattern: nil)
    /** Customer ID: Customer Identification number    This should be a unique number */
    internal var customerId: String
    /** Informative value to the request, does not have any functional impact, the value can be PREPAID/CREDIT/DEBIT */
    internal var cardType: String
    internal var account: AccountCreateBodyAccount

    internal init(customerId: String, cardType: String, account: AccountCreateBodyAccount) {
        self.customerId = customerId
        self.cardType = cardType
        self.account = account
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case customerId = "customer_id"
        case cardType = "card_type"
        case account
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(cardType, forKey: .cardType)
        try container.encode(account, forKey: .account)
    }
}

