//
// AccountListReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountListReq: Codable, JSONEncodable, Hashable {

    internal var requestListOfAccounts: RequestListOfAccounts

    internal init(requestListOfAccounts: RequestListOfAccounts) {
        self.requestListOfAccounts = requestListOfAccounts
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestListOfAccounts = "request_list_of_accounts"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestListOfAccounts, forKey: .requestListOfAccounts)
    }
}

