//
// AccountUpdateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountUpdateReq: Codable, JSONEncodable, Hashable {

    internal var requestAccountUpdate: RequestAccountUpdate

    internal init(requestAccountUpdate: RequestAccountUpdate) {
        self.requestAccountUpdate = requestAccountUpdate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestAccountUpdate = "request_account_update"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestAccountUpdate, forKey: .requestAccountUpdate)
    }
}

