//
// AccountCreateBodyAccountLimit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountCreateBodyAccountLimit: Codable, JSONEncodable, Hashable {

    static let typeRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let currencyRule = StringRule(minLength: 1, maxLength: 3, pattern: nil)
    static let valueRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    /** Credit limit type - applicable only for credit card products */
    internal var type: String?
    /** Credit limit currency - applicable only for credit card products */
    internal var currency: String?
    /** Credit limit value - applicable only for credit card products */
    internal var value: String?

    internal init(type: String? = nil, currency: String? = nil, value: String? = nil) {
        self.type = type
        self.currency = currency
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case currency
        case value
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

