//
// AccountCreateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountCreateReq: Codable, JSONEncodable, Hashable {

    internal var requestAccountCreate: RequestAccountCreate

    internal init(requestAccountCreate: RequestAccountCreate) {
        self.requestAccountCreate = requestAccountCreate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestAccountCreate = "request_account_create"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestAccountCreate, forKey: .requestAccountCreate)
    }
}

