//
// AccountHierarchyEnquiryResBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountHierarchyEnquiryResBody: Codable, JSONEncodable, Hashable {

    internal var accounts: Accounts?

    internal init(accounts: Accounts? = nil) {
        self.accounts = accounts
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case accounts
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accounts, forKey: .accounts)
    }
}

