//
// AccountHierarchyEnquiryReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AccountHierarchyEnquiryReq: Codable, JSONEncodable, Hashable {

    internal var requestAccountHierarchy: RequestAccountHierarchy

    internal init(requestAccountHierarchy: RequestAccountHierarchy) {
        self.requestAccountHierarchy = requestAccountHierarchy
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestAccountHierarchy = "request_account_hierarchy"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestAccountHierarchy, forKey: .requestAccountHierarchy)
    }
}

