//
// Balances.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Balances: Codable, JSONEncodable, Hashable {

    static let typeRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let currencyRule = StringRule(minLength: 1, maxLength: 3, pattern: nil)
    static let amountRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    /** Type of the balance */
    internal var type: String?
    /** Currency */
    internal var currency: String?
    /** Balance ammount */
    internal var amount: String?

    internal init(type: String? = nil, currency: String? = nil, amount: String? = nil) {
        self.type = type
        self.currency = currency
        self.amount = amount
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case currency
        case amount
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(amount, forKey: .amount)
    }
}

