//
// BalanceTransferBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct BalanceTransferBody: Codable, JSONEncodable, Hashable {

    internal var currency: String
    internal var amount: String
    internal var description: String
    internal var transactionRefNumber: String
    internal var planNumber: String
    internal var overrideOptions: NISrvRequestLoanonCallQuickCashOverrideOptions

    internal init(currency: String, amount: String, description: String, transactionRefNumber: String, planNumber: String, overrideOptions: NISrvRequestLoanonCallQuickCashOverrideOptions) {
        self.currency = currency
        self.amount = amount
        self.description = description
        self.transactionRefNumber = transactionRefNumber
        self.planNumber = planNumber
        self.overrideOptions = overrideOptions
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case amount
        case description
        case transactionRefNumber = "transaction_ref_number"
        case planNumber = "plan_number"
        case overrideOptions = "override_options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(amount, forKey: .amount)
        try container.encode(description, forKey: .description)
        try container.encode(transactionRefNumber, forKey: .transactionRefNumber)
        try container.encode(planNumber, forKey: .planNumber)
        try container.encode(overrideOptions, forKey: .overrideOptions)
    }
}

