//
// BalanceTrasferReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct BalanceTrasferReq: Codable, JSONEncodable, Hashable {

    internal var requestBalanceTransfer: RequestBalanceTransfer

    internal init(requestBalanceTransfer: RequestBalanceTransfer) {
        self.requestBalanceTransfer = requestBalanceTransfer
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestBalanceTransfer = "request_balance_transfer"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestBalanceTransfer, forKey: .requestBalanceTransfer)
    }
}

