//
// BalanceTrasferRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct BalanceTrasferRes: Codable, JSONEncodable, Hashable {

    internal var responseBalanceTransfer: ResponseBalanceTransfer

    internal init(responseBalanceTransfer: ResponseBalanceTransfer) {
        self.responseBalanceTransfer = responseBalanceTransfer
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseBalanceTransfer = "response_balance_transfer"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseBalanceTransfer, forKey: .responseBalanceTransfer)
    }
}

