//
// Card.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Card: Codable, JSONEncodable, Hashable {

    static let branchCodeRule = StringRule(minLength: 1, maxLength: 10, pattern: nil)
    static let cardIdentifierIdRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let cardIdentifierTypeRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    /** Branch Code, if no branches are used, the code must be same as bank_code */
    internal var branchCode: String
    /** Card Identifier Id */
    internal var cardIdentifierId: String
    /** CONTRACT_NUMBER  is used for clear card number or EXID which is a unique identifier for the card generated by CMS */
    internal var cardIdentifierType: String
    internal var customFields: [CardUpdateCustomFields]?

    internal init(branchCode: String, cardIdentifierId: String, cardIdentifierType: String, customFields: [CardUpdateCustomFields]? = nil) {
        self.branchCode = branchCode
        self.cardIdentifierId = cardIdentifierId
        self.cardIdentifierType = cardIdentifierType
        self.customFields = customFields
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case branchCode = "branch_code"
        case cardIdentifierId = "card_identifier_id"
        case cardIdentifierType = "card_identifier_type"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(branchCode, forKey: .branchCode)
        try container.encode(cardIdentifierId, forKey: .cardIdentifierId)
        try container.encode(cardIdentifierType, forKey: .cardIdentifierType)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

