//
// CardStatementSummaryReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardStatementSummaryReq: Codable, JSONEncodable, Hashable {

    internal var requestCardStatementSummary: RequestCardStatementSummary

    internal init(requestCardStatementSummary: RequestCardStatementSummary) {
        self.requestCardStatementSummary = requestCardStatementSummary
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardStatementSummary = "request_card_statement_summary"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardStatementSummary, forKey: .requestCardStatementSummary)
    }
}

