//
// CardActivationReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardActivationReq: Codable, JSONEncodable, Hashable {

    internal var requestCardActivation: RequestCardActivation

    internal init(requestCardActivation: RequestCardActivation) {
        self.requestCardActivation = requestCardActivation
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardActivation = "request_card_activation"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardActivation, forKey: .requestCardActivation)
    }
}

