//
// CardCreateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardCreateReq: Codable, JSONEncodable, Hashable {

    internal var requestCardCreate: RequestCardCreate

    internal init(requestCardCreate: RequestCardCreate) {
        self.requestCardCreate = requestCardCreate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardCreate = "request_card_create"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardCreate, forKey: .requestCardCreate)
    }
}

