//
// CardPinVerifcationRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardPinVerifcationRes: Codable, JSONEncodable, Hashable {

    internal var responseCardPinVerification: ResponseCardPinVerification

    internal init(responseCardPinVerification: ResponseCardPinVerification) {
        self.responseCardPinVerification = responseCardPinVerification
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardPinVerification = "response_card_pin_verification"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardPinVerification, forKey: .responseCardPinVerification)
    }
}

