//
// CardContactDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardContactDetails: Codable, JSONEncodable, Hashable {

    static let mobilePhoneRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let customerIdRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let emailRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let languageRule = StringRule(minLength: 1, maxLength: 5, pattern: nil)
    /** Mobile Number */
    internal var mobilePhone: String?
    /** Customer ID: Customer Identification number    This should be a unique number */
    internal var customerId: String?
    /** Email address */
    internal var email: String?
    /** Language ISO code */
    internal var language: String?

    internal init(mobilePhone: String? = nil, customerId: String? = nil, email: String? = nil, language: String? = nil) {
        self.mobilePhone = mobilePhone
        self.customerId = customerId
        self.email = email
        self.language = language
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case mobilePhone = "mobile_phone"
        case customerId = "customer_id"
        case email
        case language
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mobilePhone, forKey: .mobilePhone)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(language, forKey: .language)
    }
}

