//
// CardTransactionsReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardTransactionsReq: Codable, JSONEncodable, Hashable {

    internal var requestCardTransaction: RequestCardTransaction

    internal init(requestCardTransaction: RequestCardTransaction) {
        self.requestCardTransaction = requestCardTransaction
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardTransaction = "request_card_transaction"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardTransaction, forKey: .requestCardTransaction)
    }
}

