//
// CardPinChangeRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardPinChangeRes: Codable, JSONEncodable, Hashable {

    internal var responseCardPinChange: ResponseCardPinChange

    internal init(responseCardPinChange: ResponseCardPinChange) {
        self.responseCardPinChange = responseCardPinChange
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardPinChange = "response_card_pin_change"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardPinChange, forKey: .responseCardPinChange)
    }
}

