//
// CardContactDetailsReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardContactDetailsReq: Codable, JSONEncodable, Hashable {

    internal var requestCardContactDetails: RequestCardContactDetails

    internal init(requestCardContactDetails: RequestCardContactDetails) {
        self.requestCardContactDetails = requestCardContactDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardContactDetails = "request_card_contact_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardContactDetails, forKey: .requestCardContactDetails)
    }
}

