//
// CardDetailsRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardDetailsRes: Codable, JSONEncodable, Hashable {

    internal var responseCardDetails: ResponseCardDetails

    internal init(responseCardDetails: ResponseCardDetails) {
        self.responseCardDetails = responseCardDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardDetails = "response_card_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardDetails, forKey: .responseCardDetails)
    }
}

