//
// CardUpdateRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardUpdateRes: Codable, JSONEncodable, Hashable {

    internal var responseCardUpdate: ResponseCardUpdate

    internal init(responseCardUpdate: ResponseCardUpdate) {
        self.responseCardUpdate = responseCardUpdate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardUpdate = "response_card_update"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardUpdate, forKey: .responseCardUpdate)
    }
}

