//
// CardSetPinRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardSetPinRes: Codable, JSONEncodable, Hashable {

    internal var responseCardSetPin: ResponseCardSetPin

    internal init(responseCardSetPin: ResponseCardSetPin) {
        self.responseCardSetPin = responseCardSetPin
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardSetPin = "response_card_set_pin"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardSetPin, forKey: .responseCardSetPin)
    }
}

