//
// CardDetailsSecuredRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardDetailsSecuredRequest: Codable, JSONEncodable, Hashable {

    /** Public Key which will be used to encrypt the PAN and CVV2. This public key must be directly linked to the private key you will use to decrypt the PAN and CVV2 in your application. Supported Encryption:   RSA(4096)  */
    internal var publicKey: String

    internal init(publicKey: String) {
        self.publicKey = publicKey
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case publicKey
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publicKey, forKey: .publicKey)
    }
}

