//
// CardCreateBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardCreateBody: Codable, JSONEncodable, Hashable {

    static let customerIdRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let accountNumberRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    static let cardTypeRule = StringRule(minLength: 1, maxLength: 7, pattern: nil)
    /** Customer ID: Customer Identification number    This should be a unique number */
    internal var customerId: String
    /** Account number */
    internal var accountNumber: String
    /** Informative value to the request, does not have any functional impact, the value can be PREPAID/CREDIT/DEBIT */
    internal var cardType: String
    internal var card: CardCreateBodyCard

    internal init(customerId: String, accountNumber: String, cardType: String, card: CardCreateBodyCard) {
        self.customerId = customerId
        self.accountNumber = accountNumber
        self.cardType = cardType
        self.card = card
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case customerId = "customer_id"
        case accountNumber = "account_number"
        case cardType = "card_type"
        case card
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(accountNumber, forKey: .accountNumber)
        try container.encode(cardType, forKey: .cardType)
        try container.encode(card, forKey: .card)
    }
}

