//
// CardPinVerifcationReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardPinVerifcationReq: Codable, JSONEncodable, Hashable {

    internal var requestCardPinVerification: RequestCardPinVerification

    internal init(requestCardPinVerification: RequestCardPinVerification) {
        self.requestCardPinVerification = requestCardPinVerification
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardPinVerification = "request_card_pin_verification"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardPinVerification, forKey: .requestCardPinVerification)
    }
}

