//
// CardDetailsEnquiryReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardDetailsEnquiryReq: Codable, JSONEncodable, Hashable {

    internal var requestCardDetails: RequestCardDetails

    internal init(requestCardDetails: RequestCardDetails) {
        self.requestCardDetails = requestCardDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardDetails = "request_card_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardDetails, forKey: .requestCardDetails)
    }
}

