//
// CardUpdateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardUpdateReq: Codable, JSONEncodable, Hashable {

    internal var requestCardUpdate: RequestCardUpdate

    internal init(requestCardUpdate: RequestCardUpdate) {
        self.requestCardUpdate = requestCardUpdate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardUpdate = "request_card_update"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardUpdate, forKey: .requestCardUpdate)
    }
}

