//
// CardLimitChangeRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardLimitChangeRes: Codable, JSONEncodable, Hashable {

    internal var responseCardLimitChange: ResponseCardLimitChange

    internal init(responseCardLimitChange: ResponseCardLimitChange) {
        self.responseCardLimitChange = responseCardLimitChange
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardLimitChange = "response_card_limit_change"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardLimitChange, forKey: .responseCardLimitChange)
    }
}

