//
// CardListRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardListRes: Codable, JSONEncodable, Hashable {

    internal var responseListOfCards: ResponseListOfCards

    internal init(responseListOfCards: ResponseListOfCards) {
        self.responseListOfCards = responseListOfCards
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseListOfCards = "response_list_of_cards"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseListOfCards, forKey: .responseListOfCards)
    }
}

