//
// CardContactDetailsRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardContactDetailsRes: Codable, JSONEncodable, Hashable {

    internal var responseCardContactDetails: ResponseCardContactDetails

    internal init(responseCardContactDetails: ResponseCardContactDetails) {
        self.responseCardContactDetails = responseCardContactDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardContactDetails = "response_card_contact_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardContactDetails, forKey: .responseCardContactDetails)
    }
}

