//
// CardLookupResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardLookupResponse: Codable, JSONEncodable, Hashable {

    /** Card Identifier Type:  * `EXID` - External Id  * `CONTRACT_NUMBER` - Clear PAN  */
    internal var cardIdentifierType: CardIdentifierType?
    /** Identifier related to the Identifier Type  */
    internal var cardIdentifierId: String?

    internal init(cardIdentifierType: CardIdentifierType? = nil, cardIdentifierId: String? = nil) {
        self.cardIdentifierType = cardIdentifierType
        self.cardIdentifierId = cardIdentifierId
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case cardIdentifierType = "card_identifier_type"
        case cardIdentifierId = "card_identifier_id"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cardIdentifierType, forKey: .cardIdentifierType)
        try container.encodeIfPresent(cardIdentifierId, forKey: .cardIdentifierId)
    }
}

