//
// CardStatusChangeReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardStatusChangeReq: Codable, JSONEncodable, Hashable {

    internal var requestCardStatusChange: RequestCardStatusChange

    internal init(requestCardStatusChange: RequestCardStatusChange) {
        self.requestCardStatusChange = requestCardStatusChange
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestCardStatusChange = "request_card_status_change"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestCardStatusChange, forKey: .requestCardStatusChange)
    }
}

