//
// CardTransactionsRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardTransactionsRes: Codable, JSONEncodable, Hashable {

    internal var responseCardTransaction: ResponseCardTransaction

    internal init(responseCardTransaction: ResponseCardTransaction) {
        self.responseCardTransaction = responseCardTransaction
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardTransaction = "response_card_transaction"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardTransaction, forKey: .responseCardTransaction)
    }
}

