//
// CardStatementSummaryRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CardStatementSummaryRes: Codable, JSONEncodable, Hashable {

    internal var responseCardStatementSummary: ResponseCardStatementSummary

    internal init(responseCardStatementSummary: ResponseCardStatementSummary) {
        self.responseCardStatementSummary = responseCardStatementSummary
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseCardStatementSummary = "response_card_statement_summary"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseCardStatementSummary, forKey: .responseCardStatementSummary)
    }
}

