//
// ClientCreateBodyContactDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ClientCreateBodyContactDetails: Codable, JSONEncodable, Hashable {

    static let homePhoneRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let workPhoneRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let mobilePhoneRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let emailRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    /** Home phone */
    internal var homePhone: String?
    /** Work phone */
    internal var workPhone: String?
    /** Mobile phone */
    internal var mobilePhone: String
    /** Email */
    internal var email: String?

    internal init(homePhone: String? = nil, workPhone: String? = nil, mobilePhone: String, email: String? = nil) {
        self.homePhone = homePhone
        self.workPhone = workPhone
        self.mobilePhone = mobilePhone
        self.email = email
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case homePhone = "home_phone"
        case workPhone = "work_phone"
        case mobilePhone = "mobile_phone"
        case email
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(homePhone, forKey: .homePhone)
        try container.encodeIfPresent(workPhone, forKey: .workPhone)
        try container.encode(mobilePhone, forKey: .mobilePhone)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

