//
// ClientUpdateRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ClientUpdateRes: Codable, JSONEncodable, Hashable {

    internal var responseClientUpdate: ResponseClientUpdate

    internal init(responseClientUpdate: ResponseClientUpdate) {
        self.responseClientUpdate = responseClientUpdate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseClientUpdate = "response_client_update"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseClientUpdate, forKey: .responseClientUpdate)
    }
}

