//
// ClientUpdateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ClientUpdateReq: Codable, JSONEncodable, Hashable {

    internal var requestClientUpdate: RequestClientUpdate

    internal init(requestClientUpdate: RequestClientUpdate) {
        self.requestClientUpdate = requestClientUpdate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestClientUpdate = "request_client_update"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestClientUpdate, forKey: .requestClientUpdate)
    }
}

