//
// ClientCreateRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ClientCreateRes: Codable, JSONEncodable, Hashable {

    internal var responseClientCreate: ResponseClientCreate

    internal init(responseClientCreate: ResponseClientCreate) {
        self.responseClientCreate = responseClientCreate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseClientCreate = "response_client_create"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseClientCreate, forKey: .responseClientCreate)
    }
}

