//
// ClientCreateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ClientCreateReq: Codable, JSONEncodable, Hashable {

    internal var requestClientCreate: RequestClientCreate

    internal init(requestClientCreate: RequestClientCreate) {
        self.requestClientCreate = requestClientCreate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestClientCreate = "request_client_create"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestClientCreate, forKey: .requestClientCreate)
    }
}

