//
// EmploymentDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct EmploymentDetails: Codable, JSONEncodable, Hashable {

    static let employerNameRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    static let incomeRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    static let occupationRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    /** CompanyName */
    internal var employerName: String?
    /** Income */
    internal var income: String?
    /** Occupation/Trade */
    internal var occupation: String?

    internal init(employerName: String? = nil, income: String? = nil, occupation: String? = nil) {
        self.employerName = employerName
        self.income = income
        self.occupation = occupation
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case employerName = "employer_name"
        case income
        case occupation
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(employerName, forKey: .employerName)
        try container.encodeIfPresent(income, forKey: .income)
        try container.encodeIfPresent(occupation, forKey: .occupation)
    }
}

