//
// GetCVV2Req.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetCVV2Req: Codable, JSONEncodable, Hashable {

    internal var requestGetCvv2: RequestGetCvv2

    internal init(requestGetCvv2: RequestGetCvv2) {
        self.requestGetCvv2 = requestGetCvv2
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestGetCvv2 = "request_get_cvv2"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestGetCvv2, forKey: .requestGetCvv2)
    }
}

