//
// GetCvv2ResBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetCvv2ResBody: Codable, JSONEncodable, Hashable {

    static let cardIdentifierIdRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let cardIdentifierTypeRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let cvv2Rule = StringRule(minLength: 1, maxLength: 16, pattern: nil)
    static let expiryDateRule = StringRule(minLength: 1, maxLength: 4, pattern: nil)
    /** 454545XXXXXX1234 */
    internal var cardIdentifierId: String
    /** CONTRACT_NUMBER  is used for clear card number or EXID which is a unique identifier for the card generated by CMS */
    internal var cardIdentifierType: String
    /** Cvv2 encrypted Value */
    internal var cvv2: String
    /** Expiry Date */
    internal var expiryDate: String

    internal init(cardIdentifierId: String, cardIdentifierType: String, cvv2: String, expiryDate: String) {
        self.cardIdentifierId = cardIdentifierId
        self.cardIdentifierType = cardIdentifierType
        self.cvv2 = cvv2
        self.expiryDate = expiryDate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case cardIdentifierId = "card_identifier_id"
        case cardIdentifierType = "card_identifier_type"
        case cvv2
        case expiryDate = "expiry_date"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cardIdentifierId, forKey: .cardIdentifierId)
        try container.encode(cardIdentifierType, forKey: .cardIdentifierType)
        try container.encode(cvv2, forKey: .cvv2)
        try container.encode(expiryDate, forKey: .expiryDate)
    }
}

