//
// GetCardTransactionsReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetCardTransactionsReq: Codable, JSONEncodable, Hashable {

    internal var requestGetCardTransactions: RequestGetCardTransactions

    internal init(requestGetCardTransactions: RequestGetCardTransactions) {
        self.requestGetCardTransactions = requestGetCardTransactions
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestGetCardTransactions = "request_get_card_transactions"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestGetCardTransactions, forKey: .requestGetCardTransactions)
    }
}

