//
// GetCardTransactionsRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetCardTransactionsRes: Codable, JSONEncodable, Hashable {

    internal var responseGetCardTransactions: ResponseGetCardTransactions

    internal init(responseGetCardTransactions: ResponseGetCardTransactions) {
        self.responseGetCardTransactions = responseGetCardTransactions
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseGetCardTransactions = "response_get_card_transactions"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseGetCardTransactions, forKey: .responseGetCardTransactions)
    }
}

