//
// GetEligiblePlansReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetEligiblePlansReq: Codable, JSONEncodable, Hashable {

    internal var requestGetEligiblePlans: RequestGetEligiblePlans

    internal init(requestGetEligiblePlans: RequestGetEligiblePlans) {
        self.requestGetEligiblePlans = requestGetEligiblePlans
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestGetEligiblePlans = "request_get_eligible_plans"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestGetEligiblePlans, forKey: .requestGetEligiblePlans)
    }
}

