//
// GetEligiblePlansRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetEligiblePlansRes: Codable, JSONEncodable, Hashable {

    internal var responseGetEligiblePlans: ResponseGetEligiblePlans

    internal init(responseGetEligiblePlans: ResponseGetEligiblePlans) {
        self.responseGetEligiblePlans = responseGetEligiblePlans
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseGetEligiblePlans = "response_get_eligible_plans"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseGetEligiblePlans, forKey: .responseGetEligiblePlans)
    }
}

