//
// GetEligiblePlansResBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetEligiblePlansResBody: Codable, JSONEncodable, Hashable {

    internal var plans: [Plans]?

    internal init(plans: [Plans]? = nil) {
        self.plans = plans
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case plans
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(plans, forKey: .plans)
    }
}

