//
// GetListOfCardsResBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetListOfCardsResBody: Codable, JSONEncodable, Hashable {

    /** Either cusomer_id or account_number */
    internal var customerId: AnyCodable?
    internal var cards: [Cards]?

    internal init(customerId: AnyCodable?, cards: [Cards]? = nil) {
        self.customerId = customerId
        self.cards = cards
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case customerId = "customer_id"
        case cards
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customerId, forKey: .customerId)
        try container.encodeIfPresent(cards, forKey: .cards)
    }
}

