//
// GetListOfAccountsRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetListOfAccountsRes: Codable, JSONEncodable, Hashable {

    internal var responseListOfAccounts: ResponseListOfAccounts

    internal init(responseListOfAccounts: ResponseListOfAccounts) {
        self.responseListOfAccounts = responseListOfAccounts
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseListOfAccounts = "response_list_of_accounts"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseListOfAccounts, forKey: .responseListOfAccounts)
    }
}

