//
// GetLimitUsageDetailsReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetLimitUsageDetailsReq: Codable, JSONEncodable, Hashable {

    internal var requestGetLimiterUsageDetails: RequestGetLimiterUsageDetails

    internal init(requestGetLimiterUsageDetails: RequestGetLimiterUsageDetails) {
        self.requestGetLimiterUsageDetails = requestGetLimiterUsageDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestGetLimiterUsageDetails = "request_get_limiter_usage_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestGetLimiterUsageDetails, forKey: .requestGetLimiterUsageDetails)
    }
}

