//
// GetListOfCardsBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetListOfCardsBody: Codable, JSONEncodable, Hashable {

    static let customerIdRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let accountNumberRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    /** Either customer_id or account_number has to be sent */
    internal var customerId: String
    /** Account number */
    internal var accountNumber: String?

    internal init(customerId: String, accountNumber: String? = nil) {
        self.customerId = customerId
        self.accountNumber = accountNumber
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case customerId = "customer_id"
        case accountNumber = "account_number"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customerId, forKey: .customerId)
        try container.encodeIfPresent(accountNumber, forKey: .accountNumber)
    }
}

