//
// GetLimitUsageDetailsRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetLimitUsageDetailsRes: Codable, JSONEncodable, Hashable {

    internal var responseGetLimiterUsageDetails: ResponseGetLimiterUsageDetails

    internal init(responseGetLimiterUsageDetails: ResponseGetLimiterUsageDetails) {
        self.responseGetLimiterUsageDetails = responseGetLimiterUsageDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseGetLimiterUsageDetails = "response_get_limiter_usage_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseGetLimiterUsageDetails, forKey: .responseGetLimiterUsageDetails)
    }
}

