//
// GetPlanListResBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetPlanListResBody: Codable, JSONEncodable, Hashable {

    internal var instalments: [Instalments]?

    internal init(instalments: [Instalments]? = nil) {
        self.instalments = instalments
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case instalments
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(instalments, forKey: .instalments)
    }
}

