//
// GetRestrictionsRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetRestrictionsRes: Codable, JSONEncodable, Hashable {

    internal var responseGetRestrictionUsageDetails: ResponseGetRestrictions

    internal init(responseGetRestrictionUsageDetails: ResponseGetRestrictions) {
        self.responseGetRestrictionUsageDetails = responseGetRestrictionUsageDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseGetRestrictionUsageDetails = "response_get_restriction_usage_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseGetRestrictionUsageDetails, forKey: .responseGetRestrictionUsageDetails)
    }
}

