//
// GetRestrictionsReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GetRestrictionsReq: Codable, JSONEncodable, Hashable {

    internal var requestGetRestrictionUsageDetails: RequestGetRestrictions

    internal init(requestGetRestrictionUsageDetails: RequestGetRestrictions) {
        self.requestGetRestrictionUsageDetails = requestGetRestrictionUsageDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestGetRestrictionUsageDetails = "request_get_restriction_usage_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestGetRestrictionUsageDetails, forKey: .requestGetRestrictionUsageDetails)
    }
}

