//
// Limits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Limits: Codable, JSONEncodable, Hashable {

    internal var type: String?
    internal var currency: String?
    internal var value: String?

    internal init(type: String? = nil, currency: String? = nil, value: String? = nil) {
        self.type = type
        self.currency = currency
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case currency
        case value
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

