//
// LookupCardIdentifierResBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct LookupCardIdentifierResBody: Codable, JSONEncodable, Hashable {

    static let cardIdentifierTypeRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let cardIdentifierIdRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    /** CONTRACT_NUMBER is used for clear card number or EXID which is a unique identifier for the card generated by CMS */
    internal var cardIdentifierType: String
    /** EXID */
    internal var cardIdentifierId: String

    internal init(cardIdentifierType: String, cardIdentifierId: String) {
        self.cardIdentifierType = cardIdentifierType
        self.cardIdentifierId = cardIdentifierId
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case cardIdentifierType = "card_identifier_type"
        case cardIdentifierId = "card_identifier_id"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cardIdentifierType, forKey: .cardIdentifierType)
        try container.encode(cardIdentifierId, forKey: .cardIdentifierId)
    }
}

