//
// LookupcardidentifierRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct LookupcardidentifierRes: Codable, JSONEncodable, Hashable {

    internal var responseLookupCardIdentifier: ResponseLookupCardIdentifier

    internal init(responseLookupCardIdentifier: ResponseLookupCardIdentifier) {
        self.responseLookupCardIdentifier = responseLookupCardIdentifier
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseLookupCardIdentifier = "response_lookup_card_identifier"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseLookupCardIdentifier, forKey: .responseLookupCardIdentifier)
    }
}

