//
// LookupcardidentifierReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct LookupcardidentifierReq: Codable, JSONEncodable, Hashable {

    internal var requestLookupCardIdentifier: RequestLookupCardIdentifier

    internal init(requestLookupCardIdentifier: RequestLookupCardIdentifier) {
        self.requestLookupCardIdentifier = requestLookupCardIdentifier
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestLookupCardIdentifier = "request_lookup_card_identifier"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestLookupCardIdentifier, forKey: .requestLookupCardIdentifier)
    }
}

