//
// PinTriesCounterResetReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct PinTriesCounterResetReq: Codable, JSONEncodable, Hashable {

    internal var requestPinCounterReset: RequestPinCounterReset

    internal init(requestPinCounterReset: RequestPinCounterReset) {
        self.requestPinCounterReset = requestPinCounterReset
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestPinCounterReset = "request_pin_counter_reset"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestPinCounterReset, forKey: .requestPinCounterReset)
    }
}

