//
// PinTriesCounterResetRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct PinTriesCounterResetRes: Codable, JSONEncodable, Hashable {

    internal var responsePinCounterReset: ResponsePinCounterReset

    internal init(responsePinCounterReset: ResponsePinCounterReset) {
        self.responsePinCounterReset = responsePinCounterReset
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responsePinCounterReset = "response_pin_counter_reset"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responsePinCounterReset, forKey: .responsePinCounterReset)
    }
}

