//
// PINViewResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct PINViewResponse: Codable, JSONEncodable, Hashable {

    /** Encrypted card PIN under the public key provided in the request of the API.  */
    internal var encryptedPin: String?

    internal init(encryptedPin: String? = nil) {
        self.encryptedPin = encryptedPin
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case encryptedPin = "encrypted_pin"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(encryptedPin, forKey: .encryptedPin)
    }
}

