//
// Plans.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Plans: Codable, JSONEncodable, Hashable {

    static let planNumberRule = StringRule(minLength: 1, maxLength: 5, pattern: nil)
    static let numberOfPortionsRule = StringRule(minLength: 1, maxLength: 18, pattern: nil)
    static let interestRule = StringRule(minLength: 1, maxLength: 1, pattern: nil)
    /** Plan number */
    internal var planNumber: String
    /** Number of portions */
    internal var numberOfPortions: String
    /** Interest */
    internal var interest: String

    internal init(planNumber: String, numberOfPortions: String, interest: String) {
        self.planNumber = planNumber
        self.numberOfPortions = numberOfPortions
        self.interest = interest
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case planNumber = "plan_number"
        case numberOfPortions = "number_of_portions"
        case interest
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(planNumber, forKey: .planNumber)
        try container.encode(numberOfPortions, forKey: .numberOfPortions)
        try container.encode(interest, forKey: .interest)
    }
}

