//
// RefinanceTransactionRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct RefinanceTransactionRes: Codable, JSONEncodable, Hashable {

    internal var responseRefinanceTransaction: ResponseRefinanceTransaction

    internal init(responseRefinanceTransaction: ResponseRefinanceTransaction) {
        self.responseRefinanceTransaction = responseRefinanceTransaction
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responseRefinanceTransaction = "response_refinance_transaction"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responseRefinanceTransaction, forKey: .responseRefinanceTransaction)
    }
}

