//
// RefinanceTransactionReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct RefinanceTransactionReq: Codable, JSONEncodable, Hashable {

    internal var requestRefinanceTransaction: RequestRefinanceTransaction

    internal init(requestRefinanceTransaction: RequestRefinanceTransaction) {
        self.requestRefinanceTransaction = requestRefinanceTransaction
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestRefinanceTransaction = "request_refinance_transaction"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestRefinanceTransaction, forKey: .requestRefinanceTransaction)
    }
}

