//
// ResponseCardCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ResponseCardCreate: Codable, JSONEncodable, Hashable {

    internal var header: CardCreateResHeader
    internal var exceptionDetails: ExceptionDetails
    internal var body: CardCreateResBody?

    internal init(header: CardCreateResHeader, exceptionDetails: ExceptionDetails, body: CardCreateResBody? = nil) {
        self.header = header
        self.exceptionDetails = exceptionDetails
        self.body = body
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case header
        case exceptionDetails = "exception_details"
        case body
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(header, forKey: .header)
        try container.encode(exceptionDetails, forKey: .exceptionDetails)
        try container.encodeIfPresent(body, forKey: .body)
    }
}

