//
// Statuses.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Statuses: Codable, JSONEncodable, Hashable {

    static let typeRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let valueRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let changedDateRule = StringRule(minLength: 1, maxLength: 10, pattern: nil)
    static let descriptionRule = StringRule(minLength: 1, maxLength: 100, pattern: nil)
    /** Status type */
    internal var type: String
    /** Status value */
    internal var value: String
    /** Date of status change */
    internal var changedDate: String
    /** Brief description */
    internal var description: String?

    internal init(type: String, value: String, changedDate: String, description: String? = nil) {
        self.type = type
        self.value = value
        self.changedDate = changedDate
        self.description = description
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
        case changedDate = "changed_date"
        case description
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
        try container.encode(changedDate, forKey: .changedDate)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

