//
// Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Status: Codable, JSONEncodable, Hashable {

    static let typeRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    static let valueRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    /** Status Type */
    internal var type: String?
    /** Status value */
    internal var value: String?

    internal init(type: String? = nil, value: String? = nil) {
        self.type = type
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

