//
// TariffDetailsReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct TariffDetailsReq: Codable, JSONEncodable, Hashable {

    internal var requestTariffDetails: RequestTariffDetails

    internal init(requestTariffDetails: RequestTariffDetails) {
        self.requestTariffDetails = requestTariffDetails
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requestTariffDetails = "request_tariff_details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestTariffDetails, forKey: .requestTariffDetails)
    }
}

