//
// UpdateLimits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct UpdateLimits: Codable, JSONEncodable, Hashable {

    static let limitTypeRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let scopeCodeRule = StringRule(minLength: 1, maxLength: 1, pattern: nil)
    static let currencyRule = StringRule(minLength: 1, maxLength: 3, pattern: nil)
    static let maxNumberRule = StringRule(minLength: 1, maxLength: 10, pattern: nil)
    static let maxSingleAmountRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let maxAmountRule = StringRule(minLength: 1, maxLength: 20, pattern: nil)
    static let startDateRule = StringRule(minLength: 10, maxLength: 10, pattern: nil)
    static let endDateRule = StringRule(minLength: 10, maxLength: 10, pattern: nil)
    /** Period */
    internal var limitType: String?
    /** Scope Code */
    internal var scopeCode: String?
    /** Currency Code */
    internal var currency: String?
    /** Number of Transactions */
    internal var maxNumber: String?
    /** Maximum in single transaction */
    internal var maxSingleAmount: String?
    /** Maximum overall limit */
    internal var maxAmount: String?
    /** Start Date */
    internal var startDate: String?
    /** End Date */
    internal var endDate: String?

    internal init(limitType: String? = nil, scopeCode: String? = nil, currency: String? = nil, maxNumber: String? = nil, maxSingleAmount: String? = nil, maxAmount: String? = nil, startDate: String? = nil, endDate: String? = nil) {
        self.limitType = limitType
        self.scopeCode = scopeCode
        self.currency = currency
        self.maxNumber = maxNumber
        self.maxSingleAmount = maxSingleAmount
        self.maxAmount = maxAmount
        self.startDate = startDate
        self.endDate = endDate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case limitType = "limit_type"
        case scopeCode = "scope_code"
        case currency
        case maxNumber = "max_number"
        case maxSingleAmount = "max_single_amount"
        case maxAmount = "max_amount"
        case startDate = "start_date"
        case endDate = "end_date"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(limitType, forKey: .limitType)
        try container.encodeIfPresent(scopeCode, forKey: .scopeCode)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(maxNumber, forKey: .maxNumber)
        try container.encodeIfPresent(maxSingleAmount, forKey: .maxSingleAmount)
        try container.encodeIfPresent(maxAmount, forKey: .maxAmount)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
    }
}

