//
// UpdateLimitUsageDetailsRes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct UpdateLimitUsageDetailsRes: Codable, JSONEncodable, Hashable {

    internal var responsUpdateUsageLimiter: ResponseUpdateLimiterUsageDetails

    internal init(responsUpdateUsageLimiter: ResponseUpdateLimiterUsageDetails) {
        self.responsUpdateUsageLimiter = responsUpdateUsageLimiter
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case responsUpdateUsageLimiter = "respons_update_usage_limiter"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(responsUpdateUsageLimiter, forKey: .responsUpdateUsageLimiter)
    }
}

