//
// AccountUpdateAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class AccountUpdateAPI {

    /**
     AccountUpdate
     
     - parameter nISrvRequestAccountUpdate: (body) Sample Description 
     - returns: NISrvResponseAccountUpdate
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2AccountUpdate(nISrvRequestAccountUpdate: NISrvRequestAccountUpdate) async throws -> NISrvResponseAccountUpdate {
        return try await postCardServicesTransactionV2AccountUpdateWithRequestBuilder(nISrvRequestAccountUpdate: nISrvRequestAccountUpdate).execute().body
    }

    /**
     AccountUpdate
     - POST /V2/cardservices/AccountUpdate
     - AccountUpdate
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestAccountUpdate: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseAccountUpdate> 
     */
    internal class func postCardServicesTransactionV2AccountUpdateWithRequestBuilder(nISrvRequestAccountUpdate: NISrvRequestAccountUpdate) -> RequestBuilder<NISrvResponseAccountUpdate> {
        let localVariablePath = "/V2/cardservices/AccountUpdate"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestAccountUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseAccountUpdate>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
