//
// AccountCreateAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class AccountCreateAPI {

    /**
     AccountCreate
     
     - parameter nISrvRequestAccountCreate: (body) Sample Description 
     - returns: NISrvResponseAccountCreate
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2AccountCreate(nISrvRequestAccountCreate: NISrvRequestAccountCreate) async throws -> NISrvResponseAccountCreate {
        return try await postCardServicesTransactionV2AccountCreateWithRequestBuilder(nISrvRequestAccountCreate: nISrvRequestAccountCreate).execute().body
    }

    /**
     AccountCreate
     - POST /V2/cardservices/AccountCreate
     - AccountCreate
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestAccountCreate: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseAccountCreate> 
     */
    internal class func postCardServicesTransactionV2AccountCreateWithRequestBuilder(nISrvRequestAccountCreate: NISrvRequestAccountCreate) -> RequestBuilder<NISrvResponseAccountCreate> {
        let localVariablePath = "/V2/cardservices/AccountCreate"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestAccountCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseAccountCreate>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
