//
// AccountHierarchyEnquiryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class AccountHierarchyEnquiryAPI {

    /**
     AccountHierarchyEnquiry
     
     - parameter nISrvResponseAccountHierarchyEnquiry: (body) Sample Description 
     - returns: NISrvResponseAccountHierarchyEnquiry
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postAccountServicesEnquiryV2AccountHierarchyEnquiry(nISrvResponseAccountHierarchyEnquiry: NISrvRequestAccountHierarchyEnquiry) async throws -> NISrvResponseAccountHierarchyEnquiry {
        return try await postAccountServicesEnquiryV2AccountHierarchyEnquiryWithRequestBuilder(nISrvResponseAccountHierarchyEnquiry: nISrvResponseAccountHierarchyEnquiry).execute().body
    }

    /**
     AccountHierarchyEnquiry
     - POST /V2/accountservices/AccountHierarchyEnquiry
     - AccountHierarchyEnquiry
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvResponseAccountHierarchyEnquiry: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseAccountHierarchyEnquiry> 
     */
    internal class func postAccountServicesEnquiryV2AccountHierarchyEnquiryWithRequestBuilder(nISrvResponseAccountHierarchyEnquiry: NISrvRequestAccountHierarchyEnquiry) -> RequestBuilder<NISrvResponseAccountHierarchyEnquiry> {
        let localVariablePath = "/V2/accountservices/AccountHierarchyEnquiry"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvResponseAccountHierarchyEnquiry)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseAccountHierarchyEnquiry>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
