//
// BalanceTransferAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class BalanceTransferAPI {

    /**
     postBalanceTransfer
     
     - parameter nISrvRequestBalanceTransfer: (body) Sample Description 
     - returns: NISrvResponseBalanceTransfer
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2BalanceTransfer(nISrvRequestBalanceTransfer: NISrvRequestBalanceTransfer) async throws -> NISrvResponseBalanceTransfer {
        return try await postCardServicesTransactionV2BalanceTransferWithRequestBuilder(nISrvRequestBalanceTransfer: nISrvRequestBalanceTransfer).execute().body
    }

    /**
     postBalanceTransfer
     - POST /V2/cardservices/BalanceTransfer
     - postBalanceTransfer
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestBalanceTransfer: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseBalanceTransfer> 
     */
    internal class func postCardServicesTransactionV2BalanceTransferWithRequestBuilder(nISrvRequestBalanceTransfer: NISrvRequestBalanceTransfer) -> RequestBuilder<NISrvResponseBalanceTransfer> {
        let localVariablePath = "/V2/cardservices/BalanceTransfer"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestBalanceTransfer)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseBalanceTransfer>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
