//
// CardDetailsEnquiryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardDetailsEnquiryAPI {

    /**
     CardDetailsEnquiry
     
     - parameter nISrvResponseCardDetails: (body) Sample Description 
     - returns: NISrvResponseCardDetails
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2LookupCardIdentifier(nISrvResponseCardDetails: NISrvRequestCardDetailsEnquiry) async throws -> NISrvResponseCardDetails {
        return try await postCardServicesTransactionV2LookupCardIdentifierWithRequestBuilder(nISrvResponseCardDetails: nISrvResponseCardDetails).execute().body
    }

    /**
     CardDetailsEnquiry
     - POST /V2/cardservices/CardDetailsEnquiry
     - CardDetailsEnquiry
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvResponseCardDetails: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardDetails> 
     */
    internal class func postCardServicesTransactionV2LookupCardIdentifierWithRequestBuilder(nISrvResponseCardDetails: NISrvRequestCardDetailsEnquiry) -> RequestBuilder<NISrvResponseCardDetails> {
        let localVariablePath = "/V2/cardservices/CardDetailsEnquiry"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvResponseCardDetails)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardDetails>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
