//
// CardStatusChangeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardStatusChangeAPI {

    /**
     CardStatusChange
     
     - parameter nISrvRequestCardStatusChange: (body) Sample Description 
     - returns: NISrvResponseCardStatusChange
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardStatusChange(nISrvRequestCardStatusChange: NISrvRequestCardStatusChange) async throws -> NISrvResponseCardStatusChange {
        return try await postCardServicesTransactionV2CardStatusChangeWithRequestBuilder(nISrvRequestCardStatusChange: nISrvRequestCardStatusChange).execute().body
    }

    /**
     CardStatusChange
     - POST /V2/cardservices/CardStatusChange
     - CardStatusChange
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardStatusChange: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardStatusChange> 
     */
    internal class func postCardServicesTransactionV2CardStatusChangeWithRequestBuilder(nISrvRequestCardStatusChange: NISrvRequestCardStatusChange) -> RequestBuilder<NISrvResponseCardStatusChange> {
        let localVariablePath = "/V2/cardservices/CardStatusChange"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardStatusChange)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardStatusChange>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
