//
// CardPinVerificationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardPinVerificationAPI {

    /**
     postCardPinVerification
     
     - parameter nISrvRequestPinVerification: (body) Sample Description 
     - returns: NISrvResponsePinVerification
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardservicesEnquiryV2Cardpinverification(nISrvRequestPinVerification: NISrvRequestPinVerification) async throws -> NISrvResponsePinVerification {
        return try await postCardservicesEnquiryV2CardpinverificationWithRequestBuilder(nISrvRequestPinVerification: nISrvRequestPinVerification).execute().body
    }

    /**
     postCardPinVerification
     - POST /V2/cardservices/CardPinVerification
     - postCardPinVerification
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestPinVerification: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponsePinVerification> 
     */
    internal class func postCardservicesEnquiryV2CardpinverificationWithRequestBuilder(nISrvRequestPinVerification: NISrvRequestPinVerification) -> RequestBuilder<NISrvResponsePinVerification> {
        let localVariablePath = "/V2/cardservices/CardPinVerification"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestPinVerification)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponsePinVerification>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
