//
// CardPinChangeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardPinChangeAPI {

    /**
     postCardPinChange
     
     - parameter nISrvRequestCardPinChange: (body) Sample Description 
     - returns: NISrvResponseCardPinChange
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardPinChange(nISrvRequestCardPinChange: NISrvRequestCardPinChange) async throws -> NISrvResponseCardPinChange {
        return try await postCardServicesTransactionV2CardPinChangeWithRequestBuilder(nISrvRequestCardPinChange: nISrvRequestCardPinChange).execute().body
    }

    /**
     postCardPinChange
     - POST /V2/cardservices/CardPinChange
     - postCardPinChange
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardPinChange: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardPinChange> 
     */
    internal class func postCardServicesTransactionV2CardPinChangeWithRequestBuilder(nISrvRequestCardPinChange: NISrvRequestCardPinChange) -> RequestBuilder<NISrvResponseCardPinChange> {
        let localVariablePath = "/V2/cardservices/CardPinChange"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardPinChange)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardPinChange>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
