//
// CardTransactionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardTransactionAPI {

    /**
     postCardTransaction
     
     - parameter nISrvRequestCardTransactions: (body) Sample Description 
     - returns: NISrvResponseCardTransactions
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardTransaction(nISrvRequestCardTransactions: NISrvRequestCardTransactions) async throws -> NISrvResponseCardTransactions {
        return try await postCardServicesTransactionV2CardTransactionWithRequestBuilder(nISrvRequestCardTransactions: nISrvRequestCardTransactions).execute().body
    }

    /**
     postCardTransaction
     - POST /V2/cardservices/CardTransaction
     - postCardTransaction
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardTransactions: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardTransactions> 
     */
    internal class func postCardServicesTransactionV2CardTransactionWithRequestBuilder(nISrvRequestCardTransactions: NISrvRequestCardTransactions) -> RequestBuilder<NISrvResponseCardTransactions> {
        let localVariablePath = "/V2/cardservices/CardTransaction"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardTransactions)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardTransactions>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
