//
// CardBalanceEnquiryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardBalanceEnquiryAPI {

    /**
     postCardBalanceEnquiry
     
     - parameter nISrvRequestCardBalances: (body) Sample Description 
     - returns: NISrvResponseCardBalanceEnquiry
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesEnquiryV2CardBalanceEnquiry(nISrvRequestCardBalances: NISrvRequestCardBalances) async throws -> NISrvResponseCardBalanceEnquiry {
        return try await postCardServicesEnquiryV2CardBalanceEnquiryWithRequestBuilder(nISrvRequestCardBalances: nISrvRequestCardBalances).execute().body
    }

    /**
     postCardBalanceEnquiry
     - POST /V2/cardservices/CardBalanceEnquiry
     - postCardBalanceEnquiry
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardBalances: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardBalanceEnquiry> 
     */
    internal class func postCardServicesEnquiryV2CardBalanceEnquiryWithRequestBuilder(nISrvRequestCardBalances: NISrvRequestCardBalances) -> RequestBuilder<NISrvResponseCardBalanceEnquiry> {
        let localVariablePath = "/V2/cardservices/CardBalanceEnquiry"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardBalances)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardBalanceEnquiry>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
