//
// CardActivationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardActivationAPI {

    /**
     CardActivation
     
     - parameter nISrvRequestCardActivation: (body) Sample Description 
     - returns: NISrvResponseCardActivation
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardActivation(nISrvRequestCardActivation: NISrvRequestCardActivation) async throws -> NISrvResponseCardActivation {
        return try await postCardServicesTransactionV2CardActivationWithRequestBuilder(nISrvRequestCardActivation: nISrvRequestCardActivation).execute().body
    }

    /**
     CardActivation
     - POST /V2/cardservices/CardActivation
     - CardActivation
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardActivation: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardActivation> 
     */
    internal class func postCardServicesTransactionV2CardActivationWithRequestBuilder(nISrvRequestCardActivation: NISrvRequestCardActivation) -> RequestBuilder<NISrvResponseCardActivation> {
        let localVariablePath = "/V2/cardservices/CardActivation"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardActivation)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardActivation>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
