//
// CardLimitChangeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardLimitChangeAPI {

    /**
     postCardLimitChange
     
     - parameter nISrvRequestCardLimitChange: (body) Sample Description 
     - returns: NISrvResponseCardLimitChange
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardLimitChange(nISrvRequestCardLimitChange: NISrvRequestCardLimitChange) async throws -> NISrvResponseCardLimitChange {
        return try await postCardServicesTransactionV2CardLimitChangeWithRequestBuilder(nISrvRequestCardLimitChange: nISrvRequestCardLimitChange).execute().body
    }

    /**
     postCardLimitChange
     - POST /V2/cardservices/CardLimitChange
     - postCardLimitChange
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardLimitChange: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardLimitChange> 
     */
    internal class func postCardServicesTransactionV2CardLimitChangeWithRequestBuilder(nISrvRequestCardLimitChange: NISrvRequestCardLimitChange) -> RequestBuilder<NISrvResponseCardLimitChange> {
        let localVariablePath = "/V2/cardservices/CardLimitChange"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardLimitChange)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardLimitChange>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
