//
// CardSetPinAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardSetPinAPI {

    /**
     CardSetPin
     
     - parameter nISrvRequestCardSetPin: (body) Sample Description 
     - returns: NISrvResponseCardSetPin
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardSetPin(nISrvRequestCardSetPin: NISrvRequestCardSetPin) async throws -> NISrvResponseCardSetPin {
        return try await postCardServicesTransactionV2CardSetPinWithRequestBuilder(nISrvRequestCardSetPin: nISrvRequestCardSetPin).execute().body
    }

    /**
     CardSetPin
     - POST /V2/cardservices/CardSetPin
     - CardSetPin
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardSetPin: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardSetPin> 
     */
    internal class func postCardServicesTransactionV2CardSetPinWithRequestBuilder(nISrvRequestCardSetPin: NISrvRequestCardSetPin) -> RequestBuilder<NISrvResponseCardSetPin> {
        let localVariablePath = "/V2/cardservices/CardSetPin"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardSetPin)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardSetPin>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
