//
// CardStatementSummaryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardStatementSummaryAPI {

    /**
     postCardStatementSummary
     
     - parameter nISrvRequestCardStatementSummary: (body) Sample Description 
     - returns: NISrvResponseCardStatementSummary
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardservicesEnquiryV2Cardstatementsummary(nISrvRequestCardStatementSummary: NISrvRequestCardStatementSummary) async throws -> NISrvResponseCardStatementSummary {
        return try await postCardservicesEnquiryV2CardstatementsummaryWithRequestBuilder(nISrvRequestCardStatementSummary: nISrvRequestCardStatementSummary).execute().body
    }

    /**
     postCardStatementSummary
     - POST /V2/cardservices/CardStatementSummary
     - postCardStatementSummary
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardStatementSummary: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardStatementSummary> 
     */
    internal class func postCardservicesEnquiryV2CardstatementsummaryWithRequestBuilder(nISrvRequestCardStatementSummary: NISrvRequestCardStatementSummary) -> RequestBuilder<NISrvResponseCardStatementSummary> {
        let localVariablePath = "/V2/cardservices/CardStatementSummary"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardStatementSummary)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardStatementSummary>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
