//
// CardContactDetailsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardContactDetailsAPI {

    /**
     CardContactDetails
     
     - parameter nISrvResponseCardContactDetails: (body) Sample Description 
     - returns: NISrvResponseCardContactDetails
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesEnquiryV2CardContactDetails(nISrvResponseCardContactDetails: NISrvRequestCardContactDetails) async throws -> NISrvResponseCardContactDetails {
        return try await postCardServicesEnquiryV2CardContactDetailsWithRequestBuilder(nISrvResponseCardContactDetails: nISrvResponseCardContactDetails).execute().body
    }

    /**
     CardContactDetails
     - POST /V2/cardservices/CardContactDetails
     - CardContactDetails
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvResponseCardContactDetails: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardContactDetails> 
     */
    internal class func postCardServicesEnquiryV2CardContactDetailsWithRequestBuilder(nISrvResponseCardContactDetails: NISrvRequestCardContactDetails) -> RequestBuilder<NISrvResponseCardContactDetails> {
        let localVariablePath = "/V2/cardservices/CardContactDetails"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvResponseCardContactDetails)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardContactDetails>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
