//
// CardUpdateAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardUpdateAPI {

    /**
     postCardUpdate
     
     - parameter nISrvRequestCardUpdate: (body) Sample Description 
     - returns: NISrvResponseCardUpdate
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardUpdate(nISrvRequestCardUpdate: NISrvRequestCardUpdate) async throws -> NISrvResponseCardUpdate {
        return try await postCardServicesTransactionV2CardUpdateWithRequestBuilder(nISrvRequestCardUpdate: nISrvRequestCardUpdate).execute().body
    }

    /**
     postCardUpdate
     - POST /V2/cardservices/CardUpdate
     - postCardUpdate
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardUpdate: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardUpdate> 
     */
    internal class func postCardServicesTransactionV2CardUpdateWithRequestBuilder(nISrvRequestCardUpdate: NISrvRequestCardUpdate) -> RequestBuilder<NISrvResponseCardUpdate> {
        let localVariablePath = "/V2/cardservices/CardUpdate"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardUpdate>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
