//
// CardCreateAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CardCreateAPI {

    /**
     CardCreate
     
     - parameter nISrvRequestCardCreate: (body) Sample Description 
     - returns: NISrvResponseCardCreate
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardCreate(nISrvRequestCardCreate: NISrvRequestCardCreate) async throws -> NISrvResponseCardCreate {
        return try await postCardServicesTransactionV2CardCreateWithRequestBuilder(nISrvRequestCardCreate: nISrvRequestCardCreate).execute().body
    }

    /**
     CardCreate
     - POST /V2/cardservices/CardCreate
     - CardCreate
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardCreate: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardCreate> 
     */
    internal class func postCardServicesTransactionV2CardCreateWithRequestBuilder(nISrvRequestCardCreate: NISrvRequestCardCreate) -> RequestBuilder<NISrvResponseCardCreate> {
        let localVariablePath = "/V2/cardservices/CardCreate"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardCreate>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
