//
// ClientUpdateAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class ClientUpdateAPI {

    /**
     ClientUpdate
     
     - parameter nISrvRequestClientUpdate: (body) Sample Description 
     - returns: NISrvResponseClientUpdate
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2ClientUpdate(nISrvRequestClientUpdate: NISrvRequestClientUpdate) async throws -> NISrvResponseClientUpdate {
        return try await postCardServicesTransactionV2ClientUpdateWithRequestBuilder(nISrvRequestClientUpdate: nISrvRequestClientUpdate).execute().body
    }

    /**
     ClientUpdate
     - POST /V2/cardservices/ClientUpdate
     - ClientUpdate
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestClientUpdate: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseClientUpdate> 
     */
    internal class func postCardServicesTransactionV2ClientUpdateWithRequestBuilder(nISrvRequestClientUpdate: NISrvRequestClientUpdate) -> RequestBuilder<NISrvResponseClientUpdate> {
        let localVariablePath = "/V2/cardservices/ClientUpdate"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestClientUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseClientUpdate>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
