//
// CustomerDetailsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CustomerDetailsAPI {

    /**
     CustomerDetails
     
     - parameter nISrvRequestCustomerDetails: (body) Sample Description 
     - returns: NISrvResponseCustomerDetails
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CustomerDetails(nISrvRequestCustomerDetails: NISrvRequestCustomerDetails) async throws -> NISrvResponseCustomerDetails {
        return try await postCardServicesTransactionV2CustomerDetailsWithRequestBuilder(nISrvRequestCustomerDetails: nISrvRequestCustomerDetails).execute().body
    }

    /**
     CustomerDetails
     - POST /V2/cardservices/CustomerDetails
     - CustomerDetails
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCustomerDetails: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCustomerDetails> 
     */
    internal class func postCardServicesTransactionV2CustomerDetailsWithRequestBuilder(nISrvRequestCustomerDetails: NISrvRequestCustomerDetails) -> RequestBuilder<NISrvResponseCustomerDetails> {
        let localVariablePath = "/V2/cardservices/CustomerDetails"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCustomerDetails)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCustomerDetails>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
