//
// GetCardTransactionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class GetCardTransactionsAPI {

    /**
     GetCardTransactions
     
     - parameter nISrvRequestGetCardTransactions: (body) Sample Description 
     - returns: NISrvResponseGetCardTransactions
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2GetCardTransactions(nISrvRequestGetCardTransactions: NISrvRequestGetCardTransactions) async throws -> NISrvResponseGetCardTransactions {
        return try await postCardServicesTransactionV2GetCardTransactionsWithRequestBuilder(nISrvRequestGetCardTransactions: nISrvRequestGetCardTransactions).execute().body
    }

    /**
     GetCardTransactions
     - POST /V2/cardservices/GetCardTransactions
     - GetCardTransactions
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetCardTransactions: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseGetCardTransactions> 
     */
    internal class func postCardServicesTransactionV2GetCardTransactionsWithRequestBuilder(nISrvRequestGetCardTransactions: NISrvRequestGetCardTransactions) -> RequestBuilder<NISrvResponseGetCardTransactions> {
        let localVariablePath = "/V2/cardservices/GetCardTransactions"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetCardTransactions)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseGetCardTransactions>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
