//
// GetEligiblePlansAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class GetEligiblePlansAPI {

    /**
     postGetEligiblePlans
     
     - parameter nISrvRequestGetEligiblePlans: (body) Sample Description 
     - returns: NISrvResponseGetEligiblePlans
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesEnquiryV2GetEligiblePlans(nISrvRequestGetEligiblePlans: NISrvRequestGetEligiblePlans) async throws -> NISrvResponseGetEligiblePlans {
        return try await postCardServicesEnquiryV2GetEligiblePlansWithRequestBuilder(nISrvRequestGetEligiblePlans: nISrvRequestGetEligiblePlans).execute().body
    }

    /**
     postGetEligiblePlans
     - POST /V2/cardservices/GetEligiblePlans
     - postGetEligiblePlans
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetEligiblePlans: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseGetEligiblePlans> 
     */
    internal class func postCardServicesEnquiryV2GetEligiblePlansWithRequestBuilder(nISrvRequestGetEligiblePlans: NISrvRequestGetEligiblePlans) -> RequestBuilder<NISrvResponseGetEligiblePlans> {
        let localVariablePath = "/V2/cardservices/GetEligiblePlans"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetEligiblePlans)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseGetEligiblePlans>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
