//
// GetListOfCardsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class GetListOfCardsAPI {

    /**
     GetListOfCards
     
     - parameter nISrvRequestGetListOfCards: (body) Sample Description 
     - returns: NISrvResponseGetListOfCards
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2GetListOfCards(nISrvRequestGetListOfCards: NISrvRequestGetListOfCards) async throws -> NISrvResponseGetListOfCards {
        return try await postCardServicesTransactionV2GetListOfCardsWithRequestBuilder(nISrvRequestGetListOfCards: nISrvRequestGetListOfCards).execute().body
    }

    /**
     GetListOfCards
     - POST /V2/cardservices/GetListOfCards
     - GetListOfCards
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetListOfCards: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseGetListOfCards> 
     */
    internal class func postCardServicesTransactionV2GetListOfCardsWithRequestBuilder(nISrvRequestGetListOfCards: NISrvRequestGetListOfCards) -> RequestBuilder<NISrvResponseGetListOfCards> {
        let localVariablePath = "/V2/cardservices/GetListOfCards"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetListOfCards)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseGetListOfCards>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
