//
// GetListOfAccountsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class GetListOfAccountsAPI {

    /**
     GetListOfAccounts
     
     - parameter nISrvRequestGetListOfAccounts: (body) Sample Description 
     - returns: NISrvResponseGetListOfAccounts
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2GetListOfAccounts(nISrvRequestGetListOfAccounts: NISrvRequestGetListOfAccounts) async throws -> NISrvResponseGetListOfAccounts {
        return try await postCardServicesTransactionV2GetListOfAccountsWithRequestBuilder(nISrvRequestGetListOfAccounts: nISrvRequestGetListOfAccounts).execute().body
    }

    /**
     GetListOfAccounts
     - POST /V2/cardservices/GetListOfAccounts
     - GetListOfAccounts
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetListOfAccounts: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseGetListOfAccounts> 
     */
    internal class func postCardServicesTransactionV2GetListOfAccountsWithRequestBuilder(nISrvRequestGetListOfAccounts: NISrvRequestGetListOfAccounts) -> RequestBuilder<NISrvResponseGetListOfAccounts> {
        let localVariablePath = "/V2/cardservices/GetListOfAccounts"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetListOfAccounts)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseGetListOfAccounts>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
