//
// GetLimitUsageDetailsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class GetLimitUsageDetailsAPI {

    /**
     postGetLimiteUsageDetails
     
     - parameter nISrvRequestGetLimitUsageDetails: (body) Sample Description 
     - returns: NISrvResponseGetLimitUsageDetails
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardservicesEnquiryV2Getlimits(nISrvRequestGetLimitUsageDetails: NISrvRequestGetLimitUsageDetails) async throws -> NISrvResponseGetLimitUsageDetails {
        return try await postCardservicesEnquiryV2GetlimitsWithRequestBuilder(nISrvRequestGetLimitUsageDetails: nISrvRequestGetLimitUsageDetails).execute().body
    }

    /**
     postGetLimiteUsageDetails
     - POST /cardservices/enquiry/v2/getlimits
     - postGetLimiteUsageDetails
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetLimitUsageDetails: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseGetLimitUsageDetails> 
     */
    internal class func postCardservicesEnquiryV2GetlimitsWithRequestBuilder(nISrvRequestGetLimitUsageDetails: NISrvRequestGetLimitUsageDetails) -> RequestBuilder<NISrvResponseGetLimitUsageDetails> {
        let localVariablePath = "/cardservices/enquiry/v2/getlimits"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetLimitUsageDetails)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseGetLimitUsageDetails>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
