//
// GetPlanListAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class GetPlanListAPI {

    /**
     postGetPlanList
     
     - parameter nISrvRequestGetPlanList: (body) Sample Description 
     - returns: NISrvResponseGetPlanList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesEnquiryV2GetPlanList(nISrvRequestGetPlanList: NISrvRequestGetPlanList) async throws -> NISrvResponseGetPlanList {
        return try await postCardServicesEnquiryV2GetPlanListWithRequestBuilder(nISrvRequestGetPlanList: nISrvRequestGetPlanList).execute().body
    }

    /**
     postGetPlanList
     - POST /V2/cardservices/GetPlanList
     - postGetPlanList
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetPlanList: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseGetPlanList> 
     */
    internal class func postCardServicesEnquiryV2GetPlanListWithRequestBuilder(nISrvRequestGetPlanList: NISrvRequestGetPlanList) -> RequestBuilder<NISrvResponseGetPlanList> {
        let localVariablePath = "/V2/cardservices/GetPlanList"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetPlanList)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseGetPlanList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
