//
// GetRestrictionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class GetRestrictionsAPI {

    /**
     GetRestrictions
     
     - parameter nISrvRequestGetLimitUsageDetails: (body) Sample Description 
     - returns: NISrvResponseGetRestrictions
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardservicesEnquiryV2GetRestrictions(nISrvRequestGetLimitUsageDetails: NISrvRequestGetRestrictions) async throws -> NISrvResponseGetRestrictions {
        return try await postCardservicesEnquiryV2GetRestrictionsWithRequestBuilder(nISrvRequestGetLimitUsageDetails: nISrvRequestGetLimitUsageDetails).execute().body
    }

    /**
     GetRestrictions
     - POST /cardservices/enquiry/v2/GetRestrictions
     - GetRestrictions
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetLimitUsageDetails: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseGetRestrictions> 
     */
    internal class func postCardservicesEnquiryV2GetRestrictionsWithRequestBuilder(nISrvRequestGetLimitUsageDetails: NISrvRequestGetRestrictions) -> RequestBuilder<NISrvResponseGetRestrictions> {
        let localVariablePath = "/cardservices/enquiry/v2/GetRestrictions"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetLimitUsageDetails)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseGetRestrictions>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
