//
// GetTariffDetailsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class GetTariffDetailsAPI {

    /**
     GetTariffDetails
     
     - parameter nISrvResponseTariffDetails: (body) Sample Description 
     - returns: NISrvResponseTariffDetails
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesEnquiryV2GetTariffDetails(nISrvResponseTariffDetails: NISrvRequestTariffDetails) async throws -> NISrvResponseTariffDetails {
        return try await postCardServicesEnquiryV2GetTariffDetailsWithRequestBuilder(nISrvResponseTariffDetails: nISrvResponseTariffDetails).execute().body
    }

    /**
     GetTariffDetails
     - POST /V2/cardservices/GetTariffDetails
     - GetTariffDetails
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvResponseTariffDetails: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseTariffDetails> 
     */
    internal class func postCardServicesEnquiryV2GetTariffDetailsWithRequestBuilder(nISrvResponseTariffDetails: NISrvRequestTariffDetails) -> RequestBuilder<NISrvResponseTariffDetails> {
        let localVariablePath = "/V2/cardservices/GetTariffDetails"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvResponseTariffDetails)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseTariffDetails>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
