//
// ListOfAccountsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class ListOfAccountsAPI {

    /**
     postListOfAccounts
     
     - parameter nISrvRequestAccountList: (body) Sample Description 
     - returns: NISrvResponseAccountList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardservicesEnquiryV2Listofaccounts(nISrvRequestAccountList: NISrvRequestAccountList) async throws -> NISrvResponseAccountList {
        return try await postCardservicesEnquiryV2ListofaccountsWithRequestBuilder(nISrvRequestAccountList: nISrvRequestAccountList).execute().body
    }

    /**
     postListOfAccounts
     - POST /V2/cardservices/ListOfAccounts
     - postListOfAccounts
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestAccountList: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseAccountList> 
     */
    internal class func postCardservicesEnquiryV2ListofaccountsWithRequestBuilder(nISrvRequestAccountList: NISrvRequestAccountList) -> RequestBuilder<NISrvResponseAccountList> {
        let localVariablePath = "/V2/cardservices/ListOfAccounts"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestAccountList)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseAccountList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
