//
// ListOfCardsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class ListOfCardsAPI {

    /**
     postListOfCards
     
     - parameter nISrvRequestCardList: (body) Sample Description 
     - returns: NISrvResponseCardList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardservicesEnquiryV2Listofcards(nISrvRequestCardList: NISrvRequestCardList) async throws -> NISrvResponseCardList {
        return try await postCardservicesEnquiryV2ListofcardsWithRequestBuilder(nISrvRequestCardList: nISrvRequestCardList).execute().body
    }

    /**
     postListOfCards
     - POST /V2/cardservices/ListOfCards
     - postListOfCards
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestCardList: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseCardList> 
     */
    internal class func postCardservicesEnquiryV2ListofcardsWithRequestBuilder(nISrvRequestCardList: NISrvRequestCardList) -> RequestBuilder<NISrvResponseCardList> {
        let localVariablePath = "/V2/cardservices/ListOfCards"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestCardList)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseCardList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
