//
// LoanOnCallQuickCashAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class LoanOnCallQuickCashAPI {

    /**
     postLoanOnCallQuickCash
     
     - parameter nISrvRequestLoanonCallQuickCash: (body) Sample Description 
     - returns: NISrvRequestLoanonCallQuickCash
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2LoanOnCallQuickCash(nISrvRequestLoanonCallQuickCash: NISrvRequestLoanonCallQuickCash) async throws -> NISrvRequestLoanonCallQuickCash {
        return try await postCardServicesTransactionV2LoanOnCallQuickCashWithRequestBuilder(nISrvRequestLoanonCallQuickCash: nISrvRequestLoanonCallQuickCash).execute().body
    }

    /**
     postLoanOnCallQuickCash
     - POST /V2/cardservices/LoanOnCallQuickCash
     - postLoanOnCallQuickCash
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestLoanonCallQuickCash: (body) Sample Description 
     - returns: RequestBuilder<NISrvRequestLoanonCallQuickCash> 
     */
    internal class func postCardServicesTransactionV2LoanOnCallQuickCashWithRequestBuilder(nISrvRequestLoanonCallQuickCash: NISrvRequestLoanonCallQuickCash) -> RequestBuilder<NISrvRequestLoanonCallQuickCash> {
        let localVariablePath = "/V2/cardservices/LoanOnCallQuickCash"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestLoanonCallQuickCash)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvRequestLoanonCallQuickCash>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
