//
// LookupCardIdentifierAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class LookupCardIdentifierAPI {

    /**
     LookupCardIdentifier
     
     - parameter nISrvRequestLookupCardIdentifier: (body) Sample Description 
     - returns: NISrvResponseLookupCardIdentifier
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2CardDetailsEnquiry(nISrvRequestLookupCardIdentifier: NISrvRequestLookupCardIdentifier) async throws -> NISrvResponseLookupCardIdentifier {
        return try await postCardServicesTransactionV2CardDetailsEnquiryWithRequestBuilder(nISrvRequestLookupCardIdentifier: nISrvRequestLookupCardIdentifier).execute().body
    }

    /**
     LookupCardIdentifier
     - POST /V2/cardservices/LookupCardIdentifier
     - LookupCardIdentifier
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestLookupCardIdentifier: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseLookupCardIdentifier> 
     */
    internal class func postCardServicesTransactionV2CardDetailsEnquiryWithRequestBuilder(nISrvRequestLookupCardIdentifier: NISrvRequestLookupCardIdentifier) -> RequestBuilder<NISrvResponseLookupCardIdentifier> {
        let localVariablePath = "/V2/cardservices/LookupCardIdentifier"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestLookupCardIdentifier)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseLookupCardIdentifier>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
