//
// PinTriesCounterResetAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class PinTriesCounterResetAPI {

    /**
     PinTriesCounterReset
     
     - parameter nISrvRequestPinTriesCounterReset: (body) Sample Description 
     - returns: NISrvResponsePinTriesCounterReset
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2PinTriesCounterReset(nISrvRequestPinTriesCounterReset: NISrvRequestPinTriesCounterReset) async throws -> NISrvResponsePinTriesCounterReset {
        return try await postCardServicesTransactionV2PinTriesCounterResetWithRequestBuilder(nISrvRequestPinTriesCounterReset: nISrvRequestPinTriesCounterReset).execute().body
    }

    /**
     PinTriesCounterReset
     - POST /V2/cardservices/PinTriesCounterReset
     - PinTriesCounterReset
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestPinTriesCounterReset: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponsePinTriesCounterReset> 
     */
    internal class func postCardServicesTransactionV2PinTriesCounterResetWithRequestBuilder(nISrvRequestPinTriesCounterReset: NISrvRequestPinTriesCounterReset) -> RequestBuilder<NISrvResponsePinTriesCounterReset> {
        let localVariablePath = "/V2/cardservices/PinTriesCounterReset"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestPinTriesCounterReset)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponsePinTriesCounterReset>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
