//
// RefinanceTransactionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class RefinanceTransactionAPI {

    /**
     postRefinanceTransaction
     
     - parameter nISrvRequestRefinanceTransaction: (body) Sample Description 
     - returns: NISrvResponseRefinanceTransaction
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardServicesTransactionV2RefinanceTransaction(nISrvRequestRefinanceTransaction: NISrvRequestRefinanceTransaction) async throws -> NISrvResponseRefinanceTransaction {
        return try await postCardServicesTransactionV2RefinanceTransactionWithRequestBuilder(nISrvRequestRefinanceTransaction: nISrvRequestRefinanceTransaction).execute().body
    }

    /**
     postRefinanceTransaction
     - POST /V2/cardservices/RefinanceTransaction
     - postRefinanceTransaction
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestRefinanceTransaction: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseRefinanceTransaction> 
     */
    internal class func postCardServicesTransactionV2RefinanceTransactionWithRequestBuilder(nISrvRequestRefinanceTransaction: NISrvRequestRefinanceTransaction) -> RequestBuilder<NISrvResponseRefinanceTransaction> {
        let localVariablePath = "/V2/cardservices/RefinanceTransaction"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestRefinanceTransaction)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseRefinanceTransaction>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
