//
// SwitchRestrictionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class SwitchRestrictionsAPI {

    /**
     SwitchRestrictions
     
     - parameter nISrvRequestGetLimitUsageDetails: (body) Sample Description 
     - returns: NISrvResponseSwitchRestrictionsUsageDetails
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardservicesEnquiryV2SwitchRestrictions(nISrvRequestGetLimitUsageDetails: NISrvRequestSwitchRestrictionsUsageDetails) async throws -> NISrvResponseSwitchRestrictionsUsageDetails {
        return try await postCardservicesEnquiryV2SwitchRestrictionsWithRequestBuilder(nISrvRequestGetLimitUsageDetails: nISrvRequestGetLimitUsageDetails).execute().body
    }

    /**
     SwitchRestrictions
     - POST /cardservices/transaction/v2/SwitchRestrictions
     - SwitchRestrictions
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetLimitUsageDetails: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseSwitchRestrictionsUsageDetails> 
     */
    internal class func postCardservicesEnquiryV2SwitchRestrictionsWithRequestBuilder(nISrvRequestGetLimitUsageDetails: NISrvRequestSwitchRestrictionsUsageDetails) -> RequestBuilder<NISrvResponseSwitchRestrictionsUsageDetails> {
        let localVariablePath = "/cardservices/transaction/v2/SwitchRestrictions"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetLimitUsageDetails)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseSwitchRestrictionsUsageDetails>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
