//
// UpdateLimitUsageDetailsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class UpdateLimitUsageDetailsAPI {

    /**
     postUpdateLimiteUsageDetails
     
     - parameter nISrvRequestGetLimitUsageDetails: (body) Sample Description 
     - returns: NISrvResponseUpdateLimitUsageDetails
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func postCardservicesEnquiryV2Updatelimits(nISrvRequestGetLimitUsageDetails: NISrvRequestUpdateLimitUsageDetails) async throws -> NISrvResponseUpdateLimitUsageDetails {
        return try await postCardservicesEnquiryV2UpdatelimitsWithRequestBuilder(nISrvRequestGetLimitUsageDetails: nISrvRequestGetLimitUsageDetails).execute().body
    }

    /**
     postUpdateLimiteUsageDetails
     - POST /cardservices/transaction/v2/updatelimits
     - postUpdateLimiteUsageDetails
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter nISrvRequestGetLimitUsageDetails: (body) Sample Description 
     - returns: RequestBuilder<NISrvResponseUpdateLimitUsageDetails> 
     */
    internal class func postCardservicesEnquiryV2UpdatelimitsWithRequestBuilder(nISrvRequestGetLimitUsageDetails: NISrvRequestUpdateLimitUsageDetails) -> RequestBuilder<NISrvResponseUpdateLimitUsageDetails> {
        let localVariablePath = "/cardservices/transaction/v2/updatelimits"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: nISrvRequestGetLimitUsageDetails)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NISrvResponseUpdateLimitUsageDetails>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
